import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider} from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import '@stream-io/video-react-sdk/dist/css/styles.css';
import 'react-datepicker/dist/react-datepicker.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zoom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      variables:{
        colorText: '#fff',
        colorPrimary: '#0E78F9',
        colorBackground: '#1c1f2e',
        colorInputBackground: '#252a41',
        colorInputText: '#fff',
        colorTextOnPrimaryBackground: ''
      },
      elements:{
        socialButtonsBlockButtonText: 'text-[#fff] ',
        socialButtonsBlockButtonText__google: 'text-[#fff]',
        button: 'text-[#fff] hover:text-[#fff]',
        badge: 'text-[#fff]'
      }
    }}
    >
    <html lang='en'>
      <body className="bg-[#141824]">
        {children}
        <Toaster />
      </body>
    </html>
  </ClerkProvider>
  );
}
